Repository Team-Kappa/GraceShopper, pull requests merged in 2021-01, with the labels that each got.

#3 feat: added Test.js
  client/components/test.js
Labels: enhancement

#13 BE: Added User and Product routes
  server/api/index.js
  server/api/product.js
  server/api/users.js
Labels: enhancement

#14 FE: Added Homepage with connection to store BE: Added store for produ…
  .gitignore
  client/app.js
  client/components/homepage.js
  client/components/index.js
  client/components/test.js
  client/routes.js
  client/store/index.js
  client/store/product.js
Labels: enhancement

#16 Feat/homepage
  client/app.js
  client/components/homepage.js
  client/routes.js
  client/store/product.js
  public/images/Wine_logo2.png
  public/images/homepage_logo.png
  public/index.html
  public/style.css
Labels: enhancement

#15 FE: Added Single Wine View page & routed
  client/components/singleWineView.js
  client/routes.js
Labels: enhancement, help wanted

#22 Allwine
  client/components/allProduct.js
  client/components/index.js
  client/components/navbar.js
  client/routes.js
  client/store/index.js
  client/store/product.js
Labels: New Page, enhancement

#23 Feat/navbar
  client/app.js
  client/components/navbar.js
  client/routes.js
  package-lock.json
  package.json
  public/style.css
Labels: enhancement

#34 All Product Page Styling
  client/components/allProduct.js
  client/components/signIn.js
  public/index.html
  public/style.css
  script/seed.js
  server/db/models/index.js
  server/db/models/product.js
Labels: enhancement

#53 FE: Edited back button to material-ui
  client/components/singleWineView.js
Labels: Styling

#52 FE: Added Contact component & route, also styled contact us
  client/components/contactUs.js
  client/components/index.js
  client/components/navbar.js
  client/routes.js
  public/favicon.ico
  public/images/winery.jpeg
  public/style.css
Labels: New Page, Styling, enhancement

#64 FE: Added new logo on upper left, fixed styling issues
  client/components/contactUs.js
  client/components/navbar.js
  client/components/singleWineView.js
  public/images/grapeshopperlogo.png
  public/style.css
Labels: Styling

#67 FE: Styling Single Wine View
  client/components/singleWineView.js
  public/style.css
Labels: Styling

#68 Feat/signup/signin
  client/components/auth-form.js
  client/components/homepage.js
  client/components/navbar.js
  client/routes.js
  client/store/user.js
  public/images/homepage_banner_logo.jpg
  public/style.css
  server/auth/index.js
  server/db/models/user.js
Labels: Styling, enhancement

#75 Feat/userhomepage
  client/components/addWine.js
  client/components/auth-form.js
  client/components/checkout-panel.js
  client/components/checkout.js
  client/components/index.js
  client/components/user-home.js
  client/routes.js
  client/store/cart.js
  client/store/product.js
  public/style.css
  server/api/product.js
  server/auth/index.js
  server/db/models/user.js
Labels: enhancement

#78 FEAT: added login and sign up feature, added redirect to admin if adm…
  client/components/404.js
  client/components/index.js
  client/components/navbar.js
  client/components/user-home.js
  client/routes.js
  client/store/user.js
  public/images/wineLogo.png
  public/style.css
Labels: enhancement

#79 FE: Changed logos
  client/components/homepage.js
  client/components/navbar.js
  public/images/logoblack.png
  public/images/logoblack1.png
  public/images/logowhite.png
  public/style.css
Labels: Styling

#90 Add page style
  client/components/addWine.js
  public/style.css
Labels: Styling, enhancement

#93 Put request
  client/components/addWine.js
  client/components/auth-form.js
  client/components/editWine.js
  client/components/index.js
  client/components/navbar.js
  client/components/signUp.js
  client/components/user-home.js
  client/routes.js
  client/store/product.js
  client/store/user.js
  server/api/product.js
  server/auth/index.js
Labels: enhancement

#96 Changed class component to functional component for all product page
  client/components/allProduct.js
  client/components/checkout.js
  client/components/user-home.js
Labels: enhancement

#102 Feat/security
  README.md
  client/components/404.js
  client/components/addWine.js
  client/components/homepage.js
  client/components/user-home.js
  server/api/index.js
  server/api/order.js
  server/api/orderDetails.js
  server/api/product.js
  server/api/users.js
  server/index.js
Labels: Group work, Styling, enhancement
